version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        environment:
            APP_ENV: local
            APP_DEBUG: true
            APP_KEY: base64:your-app-key-here
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: blog
            DB_USERNAME: root
            DB_PASSWORD: root

    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: blog
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data:
