version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: blog-api
        container_name: blog_api
        restart: always
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_KEY=base64:YOUR_APP_KEY
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=secret
        depends_on:
            - db
        networks:
            - laravel_net

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_net

    artisan:
        image: blog-api
        container_name: blog_artisan
        restart: "no"
        working_dir: /var/www/html
        entrypoint: ["php", "artisan"]
        depends_on:
            - db
        networks:
            - laravel_net

    queue:
        image: blog-api
        container_name: blog_queue
        restart: always
        command: php artisan queue:work
        depends_on:
            - db
        networks:
            - laravel_net

volumes:
    mysql_data:

networks:
    laravel_net:
